name: Semgrep PR Scan

on:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto